# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iEC83JfiLoazPN274WNG_wKTiD5RpHQB
"""

try:
  x = int(input('choose a interger number: '))
  if (x % 2 == 0) == False:
    print(f'{x} is odd.')
  else:
    print(f'{x} is even.')
except ValueError:
  print("that's not a interger number.")