# -*- coding: utf-8 -*-
"""Greater_or_Lesser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RVZ76Kvw5YzOwJY2ZsPH3qALnRUIEgWI
"""

try:
  x = int(input('choose a number: '))
  y = int(input('another: '))
  if x > y:
    print(f'{x} is greater than {y}.')
  elif x < y:
    print(f'{x} is lesser than {y}.')
  else:
    print('both are equal.')
except ValueError:
  print('try again with a integer number.')