# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16DxLzkjiE06MBYyovzQ7Fs1wD5irmwyR
"""

try:
  x = float(input('choose a number: '))
  if x % 2 == 0:
    print(x ** (1/2))
  else:
    print(x * x)
except ValueError:
  print('try again with a number.')